-- us_lex/us_gaz/us_rules land in public, owned by the supautils
-- superuser. This extension has no dedicated schema of its own, so
-- this grants read access to exactly those three tables rather than a
-- schema-wide default: the database's own owner already owns the
-- public schema itself, so a schema-wide grant here would be
-- redundant with that ownership.
--
-- Granted to pg_database_owner rather than a hardcoded role name, so
-- this keeps working if the database is later reassigned to a
-- different owner. See
-- https://www.postgresql.org/docs/current/predefined-roles.html.
GRANT SELECT ON TABLE public.us_lex, public.us_gaz, public.us_rules TO pg_database_owner;
