-- The database's own owner needs USAGE on bm25_catalog to declare a
-- column of its bm25vector type and call its functions
-- (search_bm25query, to_bm25query); Postgres already grants EXECUTE on
-- new functions to PUBLIC by default, so no separate function grant is
-- needed. The schema holds only the type and its support functions, no
-- tables.
--
-- Granted to pg_database_owner rather than a hardcoded role name, so
-- this keeps working if the database is later reassigned to a
-- different owner. See
-- https://www.postgresql.org/docs/current/predefined-roles.html.
GRANT USAGE ON SCHEMA bm25_catalog TO pg_database_owner;
